<template>
		<div class="container-table">
			<table class="form-table" style="width:600px;" cellpadding="0" cellspacing="0">

				<thead class="fixed-thead">
					<tr>
						<th>序号</th>
						<th>姓名</th>
						<th>性别</th>
						<th>年龄</th>
					</tr>
				</thead>

				<tbody class="scroll-tbody">
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
					<tr>
						<td>1</td>
						<td>张三</td>
						<td>男</td>
						<td>18</td>
					</tr>
				</tbody>
			</table>
		</div>
</template>
<script>
export default {
  
}
</script>
<style>

</style>
